### ISSUE TITLE
论文剽窃问题

### ISSUE THREAD

**Issue by calabashboy-coldmoon** [zouyishan/code#1]
论文和github中capsnet的代码和实验都是我搭建并且完成的，作者以论文加名字为由骗我进行实验，拿着我的代码和成果以后却过河拆桥，我联系过作者，作者撒谎说没有用我的内容，请问这样的学术态度合适吗？

**Comment by zouyishan** [comment]
你可以加我qq聊一聊 2983748714

**Comment by calabashboy-coldmoon** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zouyishan** [comment]
实在不好意思，其中的关系有点复杂。我先关掉这个issue，你可以加我联系方式聊聊

**Comment by calabashboy-coldmoon** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
